{% set name = "plumed-metatomic" %}

# update the dev suffix whenever the git_rev changes
{% set version = "2.10.0.dev0" %}
{% set git_rev = "00b1cc034c3c66d9d18436518e2b1b11d6266843" %}

{% set build = 1 %}

# Use a higher build number for prefered variants, to ensure that they are
# picked first by conda's solver.
{% if mpi == 'nompi' %}
  {% set build = build + 1000 %}
{% endif %}

{% if mpi == 'nompi' %}
  {% set mpi_prefix = "nompi" %}
{% else %}
  {% set mpi_prefix = "mpi_" + mpi %}
{% endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/plumed/plumed2.git
  git_rev: {{ git_rev }}
  depth: 1

build:
  number: {{ build }}
  skip: true  # [win]
  string: {{ mpi_prefix }}_h{{ PKG_HASH }}_git.{{ git_rev[:7] }}_{{ build }}

  # Most programs should link libplumedWrapper.a so that libplumedKernel.so will
  # be loaded with dlopen. There is no need for pinning thus. Programs linking
  # libplumed.so should pin to min_pin='x.x', max_pin='x'. Programs linking
  # libplumedKernel.so should pin to min_pin='x.x.x'. max_pin='x.x.x'
  {% if mpi != "nompi" %}
  run_exports:
    - {{ name }} * {{ mpi_prefix }}_*
  {% endif %}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
    - make
  host:
    - {{ mpi }}  # [mpi != "nompi"]
    - fftw
    - gsl
    - libblas
    - liblapack
    - llvm-openmp  # [osx]
    - zlib
    - libmetatomic-torch >=0.1.2,<0.2.0
    # always build against the CPU version of libtorch, we can still pick the
    # cuda one at runtime
    - libtorch * cpu*
  run:
    - {{ mpi }}  # [mpi != "nompi"]
    - llvm-openmp  # [osx]
    - libtorch
    - libmetatomic-torch >=0.1.2,<0.2.0
    - libmetatensor-torch >=0.7.6,<0.8.0
    - libmetatensor >=0.1.14,<0.2.0

test:
  commands:
    - export OMPI_MCA_plm=isolated  # [mpi == "openmpi"]
    - export OMPI_MCA_btl_vader_single_copy_mechanism=none  # [mpi == "openmpi"]
    - export OMPI_MCA_rmaps_base_oversubscribe=yes  # [mpi == "openmpi"]
    - export OMPI_MCA_btl=vader,self  # [mpi == "openmpi"]
    - plumed info --root
    - plumed info --long-version
    - plumed-patch -h
    - plumed config has external_blas external_lapack fftw gsl zlib
    - plumed config has libmetatomic
    - plumed config has asmjit  # [not ppc64le and not aarch64 and not arm64]
    - plumed config has mpi  # [mpi != "nompi"]
    - $PREFIX/lib/plumed/plumed-runtime -h
    - test -f $PREFIX/lib/libplumed$SHLIB_EXT
    - test -f $PREFIX/lib/libplumedWrapper.a
    - test -f $PREFIX/lib/libplumedKernel$SHLIB_EXT

about:
  home: http://www.plumed.org/
  license: LGPL-3.0-only
  license_family: GPL
  license_file: COPYING.LESSER
  summary: Free energy calculations in molecular systems
  description: |
    PLUMED is an open source library for free energy calculations in molecular
    systems which works together with some of the most popular molecular
    dynamics engines. This version enables the metatomic integration.
  doc_url: https://docs.metatensor.org/latest/atomistic/engines/plumed.html
  dev_url: https://github.com/plumed/plumed2

extra:
  recipe-maintainers:
    - HaoZeke
    - Luthaf
